### ISSUE TITLE
Duplicate ProviderIDs

### ISSUE THREAD

**Issue by simplysoft** [sp-yduck/cluster-api-provider-proxmox#94] opened 2023-10-13 09:14 UTC
/kind bug

**What steps did you take and what happened:**
When increasing replicas count of a machine set to bigger number (e.g. 0 -> 3), causing it to create many many machines within a short amount of time, we end up with multiple `ProxmoxMachine` instances that have all the same provider ID.
In this instance where we did scale from 0 -> 3, only one single proxmox vm got created and we had 3 `ProxmoxMachine` with different names but same provider id

**What did you expect to happen:**
Individual VMs get created

**Anything else you would like to add:**
Not yet sure where this bug is coming from (cluster-api, proxmox provider or even proxmox REST API)

**Environment:**

- Cluster-api-provider-proxmox version: Latest Main
- Proxmox VE version: 8.0.4

**Comment by sp-yduck** [comment] 2023-10-13 10:47
could you share yor `proxmoxmachinetemplate` to here ?

**Comment by sp-yduck** [comment] 2023-10-13 11:52
I am not sure the cause yet but I have [fixed](https://github.com/sp-yduck/cluster-api-provider-proxmox/compare/main...improve-instance-reconciler) one potential cause. you can try this with `spyduck/cluster-api-provider-proxmox:9e7ea64` image (pushed to [docker.io](https://hub.docker.com/repository/docker/spyduck/cluster-api-provider-proxmox/general))

**Comment by simplysoft** [comment] 2023-10-13 13:20
Thanks for the hint, I'm not sure if it is related to that. Setting the VM ID once before the VM is being created does not seem to be a problem. It feels like that would be a viable approach as part of reconciliation. But the following reconciliation might not properly take that set VM id into consideration (but not sure how the internals work when a reconcilation fails, but partially updates were performed on that object, does the retrying reconciliation still operate on the old version of that document or the patched one?)

We are currently testing with a develop version that has ranged based vmid assignment (not using proxmox next id), but we have experienced this already before, but not yet re-tested with your latest change. We will see if we can re-test with that version

**Comment by sp-yduck** [comment] 2023-10-22 05:00
closing as this cannot be reproduced

**Closed by sp-yduck** 2023-10-22 05:00 UTC
Labels: bug
